# Site
repository: otanikotani/me
favicon: images/favicon.ico

# Personal info
name: Andrey Artyukhov
title: Software Engineer
email: otanikotani@gmail.com
website: www.github.com/otanikotani/me

# Social links
github_username:  otanikotani
linkedin_username: andrey-artyukhov-64423689

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Andrey and I like to call myself a software engineer. I have great experience in designing and developing backend applications for a variety of businesses - from telecom to project management systems.

  I believe I am capable to work with little to none supervision being efficient and self-disciplined. I have over 7 years fully remote working experience, allowing me to understand the principles of personal growth and motivation.

  I am most skilled in: <mark>Java</mark> and <mark>System Design</mark>

  Professional experience: 13 years

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Travelling
   - Gaming
   - Philosophy

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-pdf
