# Site
repository: otanikotani/me
favicon: images/favicon.ico

# Personal info
name: Andrei Artiukhov
title: Staff Software Engineer
email: otanikotani@gmail.com
website: www.github.com/otanikotani/me

# Social links
github_username:  otanikotani
linkedin_username: andrey-artyukhov-64423689

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hell, my name is Andrei. I am a software engineer with a passion for building scalable and reliable systems. I architect software
    solutions through DDD that are easy to maintain and extend. 
  
  My personality is INFJ-T (Advocate) - I am idealistic and principled. I want to stand up to make a difference.

  My skills: <mark>Kotlin</mark> <mark>TypeScript</mark> <mark>AWS</mark> <mark>Java Spring</mark> <mark>System Design</mark>

  Professional experience: 13 years

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Travelling
   - Gaming
   - Philosophy

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins: []

gems:
  - jekyll-pdf
